spring:
  generate-ddl: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  jpa:
    defer-datasource-initialization: true
    show-sql: true

  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true

hibernate:
  hbm2ddl:
    auto: create-drop

springdoc:
  paths-to-match: /**

logging:
  level:
    _org.springframework.web.servlet.HandlerMapping.Mappings: debug
